Feat/tips calculator
ValTM/friendly-bassoon pull request #8
Opened 2022-08-17 13:57 UTC by murito7

2022-09-27 22:01 UTC, ValTM requested changes

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/RecapContainer.jsx
> +  RecapContainer.propTypes = {
Prop types should be outside of the component, once it's defined. While it's valid JS, it makes reading the initialization of the component a bit hard. Also all other components have their prop types outside, keep a consistent placing.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/RecapContainer.jsx
> +    <div className=" bg-tipsDarkCyan mt-10 rounded-xl px-5 py-7 xl:mt-0 xl:h-[100%] xl:px-10 xl:py-10">
On multiple places you have className=" <classes>". Or you end your class list with "<classes> " extra space. While this is simple nitpicking, it leaves a bad impression.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/RecapContainer.jsx
> +      nbPeople != null ? (
The only difference here is the background color. Please, put that in the ternary, instead of the whole button.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/TipsContainer.jsx
> +    console.log(btns);
Remove console.log

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/TipsContainer.jsx
> +  TipsContainer.propTypes = {
Again, move prop types after you declare the function.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/TipsContainer.jsx
> +    let btns = Array.from(document.getElementById('btn--container').children);
Just use a ref instead of relying on IDs and `document.getElementById`. Do it the React way.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/TipsContainer.jsx
> +    if (event.target.value.length > event.target.maxLength) {
Extract `evetnt.target` and `event.target.value` to two `const`s, you're using the first one 7 times, and the second one 3 times.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/Components/TipsContainer.jsx
> +        <button
The only difference between the preset buttons is the id and the value. Create an array and map it, for example
```jsx
[5,10,15,25,50].map((value, index) => (<button ... value={value}>{value}%</button>))
```

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/invalidChar.jsx
> +export const blockInvalidChar = (e) =>
This can be a .js file, as it is simply js. No React, so .jsx is useless here.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/TipsCalculator.jsx
> +      <form className=" bg-white mt-[100px] rounded-t-[20px] p-10 xl:w-[80%] mx-auto xl:rounded-xl 2xl:w-[1100px]   ">
Why do you use a form here??? Just use a div! If you use a form and you double click any button when the form is valid it will refresh the page. If you use it for the `required` attribute on the `<input>` elements, at least prevent the default event in `handleButtonClick()` in `TipsContainer.jsx`, or do something like [this](https://stackoverflow.com/a/1818268) to prevent the page reloads.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/TipsCalculator.jsx
> +      setTipAmount(parseFloat((bill * tip) / 100 / nbPeople).toFixed(2));
You only work with numbers, why do you need to do `parseFloat` here?

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/TipsCalculator.jsx
> +  const [bill, setBill] = useState(null);
Rather set 0 as the default value in `useState` for all numbers.

2022-09-27 22:01 UTC, ValTM commented on src/pages/TipsCalculator/TipsCalculator.jsx
> +    if (bill === 0 || tip === 0 || nbPeople === 0) {
If you put 0 as default value in useState you can maybe do
`if (!bill || !tip || !nbPeople)` here.

2022-09-30 07:24 UTC, murito7 commented on src/pages/TipsCalculator/Components/TipsContainer.jsx
> +    if (event.target.value.length > event.target.maxLength) {
Only event.target can be extracted into const

2022-11-09 18:40 UTC, merged